### ISSUE TITLE
Readme documents old --recursive flag instead of --norecursive

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/rusty-hog#23]
## Description

Looks like `duroc_hog` behavior was changed such that it is [recursive by default](https://github.com/newrelic/rusty-hog/issues/13) but the readme and various other files still refer to the old `--recursive` flag instead of the new `--norecursive` flag.

## Steps to Reproduce

Running `duroc_hog` with the latest binaries and the documented recursive flag yields the following error:

```
./duroc_hog --recursive --prettyprint /path/to/repo
error: Found argument '--recursive' which wasn't expected, or isn't valid in this context
	Did you mean --norecursive?

USAGE:
    duroc_hog <FSPATH> --norecursive

For more information try --help
```

## Expected Behaviour

README documentation matches execution behavior.

## Relevant Logs / Console output

See above.

## Your Environment

```
      System Version: macOS 10.15.6 (19G73)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
```

## Additional context

None

**Comment by cutler-scott-newrelic** [comment]
Finished. Thanks for submitting this!
