### ISSUE TITLE
Rusty Hog Google Drive enhancements

### ISSUE THREAD

**Issue by danielhartnell** [newrelic/rusty-hog#27]
## Summary

Sorry, this request may be somewhat vague. Feel free to reach out to me if we need to refine this a bit. I want to record an enhancement request around Rusty Hog's ability to scan Google Drive documents. The notes I had wanted to look into providing a Drive, download the associated binary file (or files?) and scanning them.

cc @cutler-scott-newrelic in case you want to provide some additional detail in this issue. I don't have enough to provide desired behavior and possible solutions.

**Comment by cutler-scott-newrelic** [comment]
I did not realize my commit message would auto-close this. But yeah, we now have a Google Drive scanner! Unfortunately the duroc_hog binary in master is broken right now, so make sure to use this with a released binary.
