### ISSUE TITLE
Confluence secret scanner

### ISSUE THREAD

**Issue by madchap** [newrelic/rusty-hog#3]
## Summary

It'd be great to have some implementation to scan secrets within Confluence :)

**Comment by ccojocar** [comment]
I found this crate which allow to access the Confluence API https://github.com/Nercury/confluence-rs.

**Comment by cutler-scott-newrelic** [comment]
Thanks guys! I will take a look at this and try to get some work done over the next few weeks. Currently I'm not sure if I have a test instance of confluence to work with, but it looks like I can "try it for free"

**Comment by cutler-scott-newrelic** [comment]
I pushed an update to master that includes a new hog, essex_hog. It works with my company's confluence instance, but I have no idea if it works with yours. Try building master and running it against yours and let me know if it works. I am hoping to polish documentation a bit more before calling it a release so I won't close this ticket until that's done.

**Comment by cutler-scott-newrelic** [comment]
I'm actually gonna close this, but feel free to open up additional issues / tickets if you see problems.

**Comment by ccojocar** [comment]
I tested with our confluence instance and it works. Thanks for implementing this!

**Comment by madchap** [comment]
@cutler-scott-newrelic you rock! Thanks!

**Comment by patoche71** [comment]
Hello guys, got my hands on essex_hog (1.0.11) but can't make it run. Turning in circle there. Always ending up with followin error. Sounds ridiculous, but do you have a clue or an example of the command line with URL & user/password ? Thks

error: The following required arguments were not provided:
    <URL>
